[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Dependencias necesarias para el AHT10 y el sistema base
lib_deps =
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14